 
version: '3'
services:
  udagram-user:
    build:
      context: ../../Documents/sam-udagram-app/udagram-api-user
      dockerfile: Dockerfile
    image: cercuit/udagram-user
  udagram-feed:
    build:
      context: ../../Documents/sam-udagram-app/udagram-api-feed
      dockerfile: Dockerfile
    image: cercuit/udagram-feed
  reverseproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cercuit/reverseproxy
  udagram-frontend:
    build:
      context: ../../Documents/sam-udagram-app/udagram-frontend 
    image: cercuit/udagram-frontend