 apiVersion: v1
kind: ConfigMap
data:
  AWS_BUCKET: sam-530680288131-dev
  AWS_PROFILE: default
  AWS_REGION: eu-west-3
  POSTGRES_USERNAME:  cercuit
  POSTGRES_PASSWORD: 1stbillion
  POSTGRES_HOST: cdr.cipky0gxx865.eu-west-3.rds.amazonaws.com
  POSTGRES_DB: cercuitt
  JWT_SECRET: aGVsbG8K
  URL: http://localhost:8100
     

metadata:
  name: env-config